apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-server
  labels:
    app: cloud-gateway-server
spec:
  #serviceName: cloud-gateway-server
  replicas: 1
  #podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: cloud-gateway-server
  template:
    metadata:
      labels:
        app: cloud-gateway-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cloud-gateway-server
          image: touchstar.ezlink-wifi.com:30883/docker_private/cloud-gateway-server:1.0
          ports:
            - name: server
              containerPort: 9500
            - name: management
              containerPort: 8081
          env:
            - name: EUREKA_NAME
              value: "eureka"
            - name: APP_NAME
              value: "cloud-gateway-server"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --eureka.instance.instance-id=${POD_NAME}
                     --eureka.instance.hostname=${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.preferIpAddress=false
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0.${EUREKA_NAME}:8080/eureka/,http://eureka-1.${EUREKA_NAME}:8080/eureka/,http://eureka-2.${EUREKA_NAME}:8080/eureka/
                     "

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-server
  labels:
    app: cloud-gateway-server
spec:
  type: NodePort
  ports:
    - name: server
      port: 9500
      targetPort: 9500
      nodePort: 30950
  selector:
    app: cloud-gateway-server
