kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: dcp-k8s-dev
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
              subPath: storage/dcp-k8s-dev
          env:
            - name: PROVISIONER_NAME
              value: dcp/ifs
            - name: NFS_SERVER
              value: 192.168.66.171
            - name: NFS_PATH
              value: /data/k8s-nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.66.171
            path: /data/k8s-nfs