apiVersion: v1
kind: PersistentVolume
metadata:
  name: tsboss-storage
  labels:
    app: tsboss-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 118.144.105.2
    path: /data/iotupload

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tsboss-storage
  labels:
    app: tsboss-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: tsboss-storage
