apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  labels:
    app: jenkins-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080          #服务端口
    targetPort: 8080
  - name: jnlp
    port: 50000         #代理端口
    targetPort: 50000
  selector:
    app: jenkins-server
