apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-server
  labels:
    app: jenkins-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 118.144.105.2
    path: /nfs/data/jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-server
  labels:
    app: jenkins-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: jenkins-server
