apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins       #ServiceAccount名
  namespace: kube-system     #指定namespace，一定要修改成你自己的namespace
  labels:
    name: jenkins
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  labels:
    name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
