apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-service-boss
  labels:
    app: cloud-service-boss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-service-boss
  template:
    metadata:
      labels:
        app: cloud-service-boss
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cloud-service-boss
          image: touchstar.ezlink-wifi.com:30883/docker_private/cloud-service-boss:1.0
          volumeMounts:
            - name: tsboss-storage-data
              mountPath: /data/iotupload
          ports:
            - name: https
              containerPort: 5008
            - name: http
              containerPort: 5009
            - name: management
              containerPort: 8081
          env:
            - name: EUREKA_NAME
              value: "eureka"
            - name: APP_NAME
              value: "cloud-service-boss"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.hostname=${APP_NAME}
                     --eureka.instance.instance-id=${APP_NAME}
                     --eureka.instance.preferIpAddress=false
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0.${EUREKA_NAME}:8080/eureka/,http://eureka-1.${EUREKA_NAME}:8080/eureka/,http://eureka-2.${EUREKA_NAME}:8080/eureka/
                     "
      volumes:
        - name: tsboss-storage-data
          persistentVolumeClaim:
            claimName: tsboss-storage
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-service-boss
  labels:
    app: cloud-service-boss
spec:
  type: NodePort
  ports:
    - name: https
      port: 5008
      targetPort: 5008
      nodePort: 30508
      protocol: TCP
    - name: http
      port: 5009
      targetPort: 5009
      protocol: TCP
  selector:
    app: cloud-service-boss
