apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  namespace: dcp-k8s-dev
  labels:
    app: mysql-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 192.168.66.171
    path: /data/k8s-nfs/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dcp-k8s-dev
  name: mysql-storage
  labels:
    app: mysql-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: mysql-volume
