apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-service-media
  labels:
    app: cloud-service-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-service-media
  template:
    metadata:
      labels:
        app: cloud-service-media
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cloud-service-media
          image: touchstar.ezlink-wifi.com:30883/docker_private/cloud-service-media:1.0
          volumeMounts:
            - name: service-log-storage-data
              mountPath: /data/logs
          ports:
            - name: server
              containerPort: 5014
            - name: management
              containerPort: 8081
          env:
            - name: EUREKA_NAME
              value: "eureka"
            - name: APP_NAME
              value: "cloud-service-media"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JVM_OPS
              value: "
                      -Duser.timezone=Asia/Shanghai
                      -Xmx640m
                      -Xms640m
                      -Xmn256m
                      -XX:SurvivorRatio=8
                      -XX:MaxTenuringThreshold=10
                      -XX:MetaspaceSize=128m
                     "
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --feign.debug.devicecontrol
                     --feign.debug.artmarket
                     --feign.debug.launcher
                     --feign.debug.tsvod
                     --feign.debug.tslive
                     --feign.debug.passport
                     --feign.debug.persistence
                     --feign.debug.addedvalue
                     --logback.logName=${POD_NAME}
                     --eureka.instance.instance-id=${POD_NAME}
                     --eureka.instance.hostname=${APP_NAME}
                     --eureka.instance.preferIpAddress=false
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0.${EUREKA_NAME}:8080/eureka/,http://eureka-1.${EUREKA_NAME}:8080/eureka/,http://eureka-2.${EUREKA_NAME}:8080/eureka/
                     "
      volumes:
        - name: service-log-storage-data
          persistentVolumeClaim:
            claimName: service-log-storage
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-service-media
  labels:
    app: cloud-service-media
spec:
  type: ClusterIP
  ports:
    - name: server
      port: 5014
      targetPort: 5014
      protocol: TCP
  selector:
    app: cloud-service-media
