apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic-system
spec:
  version: 7.2.0
  nodeSets:
  - name: elasticesearch
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      index.store.type: niofs
    podTemplate:
      spec:
        initContainers:
        # 一定要进行系统级虚拟配置修改，否则将提示一下错误信息
        # max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard