apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonatype-nexus
  labels:
    app: sonatype-nexus
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 124.193.37.7
    path: /data/nfs/sonatype

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonatype-nexus
  labels:
    app: sonatype-nexus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: sonatype-nexus
