kind: Service
apiVersion: v1
metadata:
  name: prometheus-server-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
    nodePort: 30101
    protocol: TCP
  selector:
    app: prometheus-server-dep
