apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-log-storage
  labels:
    app: service-log-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 118.144.105.2
    path: /data/logs

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: service-log-storage
  labels:
    app: service-log-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: service-log-storage
