apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  namespace: dcp-k8s-dev
  labels:
    app: redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    server: 192.168.66.171
    path: /data/k8s-nfs/redis

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dcp-k8s-dev
  name: redis-storage
  labels:
    app: redis-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: redis-volume
