apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis-config
data:
  redis.conf: |-
    dir /data
    port 4000
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    pidfile /data/redis-4000.pid


